import { StyleSheet, Dimensions} from "react-native";

const dibujar=StyleSheet.create({
    Container:{
      width:'100%',
      padding:20
    },
    Title:{
      fontSize:20,
      color:'#008BFF',
    },
    TextInput:{
      borderColor:'#0019FF',
      borderWidth:1,
      borderRadius:15,
      width:Dimensions.get("screen").width*0.6,
      paddingLeft:10
    },
    textt:{
      fontSize:16,
      color:'#008BFF',
    },
    wtext:{
      fontSize:16,
      color:'#FF0000',
    },
    InputContainer:{
      marginTop:20,
      flexDirection:"row",
      justifyContent:"space-between"
    },
    Buttonn:{
      width:Dimensions.get("screen").width*0.2,
      backgroundColor:'#539AFF',
      justifyContent:'center',
      alignItems:'center',
      borderRadius:15
    },
    taskcontainer:{
      paddingVertical:20,
      borderBottomColor:'#8800FF',
      borderBottomWidth:10,
      flexDirection:'row',
      justifyContent:'space-between'
    },
    textodone:{
      fontSize:16,
      color:"black",
      textDecorationLine:"line-through"
    },
    removebutton:{
      backgroundColor:'#8800FF',
      justifyContent:'center',
      alignContent:'center',
      paddingHorizontal:15,
      borderRadius:10
  
    }
  })
  export default dibujar